apiVersion: apps/v1
kind: Deployment
metadata:
  granite-llm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: granite-app
  template:
    metadata:
      labels:
        app: granite-app

image:
  repository: dockerhub.io/scheckley/granite
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8443

resources:
  limits:
    cpu: '4'
    memory: '64Gi'
  requests:
    cpu: '8'
    memory: '64Gi'
    nvidia.com/gpu: '1'
    nodeName: 'ocp-8q24t-worker-gpu-a100x4-2slpc'
