apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibm-granite-llm.fullname" . }}
  labels:
    app: {{ include "ibm-granite-llm.name" . }}
    chart: {{ include "ibm-granite-llm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Add your configuration data here
  example-config: "value"
