apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-granite-llm.fullname" . }}
  labels:
    app: {{ include "ibm-granite-llm.name" . }}
    chart: {{ include "ibm-granite-llm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
  selector:
    app: {{ include "ibm-granite-llm.name" . }}
    release: {{ .Release.Name }}
